//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAppDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressTable
    {
        public AddressTable()
        {
            this.EmployeeTable = new HashSet<EmployeeTable>();
        }
        public int Id { get; set; }

        public string Details { get; set; }

        public string State { get; set; }

        public string Country { get; set; }
        public HashSet<EmployeeTable> EmployeeTable { get; }
        
    }
}
